---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: mwrock/Windows2012R2
    transport:
      name: winrm
      password: vagrant
      username: vagrant

suites:
  - name: default
    run_list:
      - recipe[windows_openssl::default]
    verifier:
      inspec_tests:
        - test/recipes
    attributes:
